let express=require("express")
let route=require("./route/route")
let mongoose=require("mongoose")
let bodyparser=require("body-parser")
let cors=require("cors")
let app=express()
app.use(express.json())
app.use(cors())
app.use("/pimages",express.static('./productimg'))
app.use(bodyparser.urlencoded({extended:true}))
mongoose.connect("mongodb://127.0.0.1:27017/ecomers").then(()=>{
    console.log("ok")
})
app.use("/",route)
app.listen(5000)